config/routes.rb
TimeClock::Application.routes.draw do
  resources :time_sheets

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resource :time_sheet do
    get '/close/:id', to: 'time_sheets#close', as: 'close'
    get :open
  end

  root to: "home#show"
end

app/models/time_sheet.rb
class TimeSheet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :time_sheets
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.picture = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if current_user
      @sheets = current_user.time_sheets.where('closed_at is not null').order(created_at: :desc)
      @today = current_user.time_sheets.where('created_at > ?', Time.now.beginning_of_day).where('closed_at is null').first
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/time_sheets_controller.rb
class TimeSheetsController < ApplicationController
  before_action :set_time_sheet, only: [:close]
  
  def close
    @time_sheet.update_attributes(closed_at: Time.now)
    redirect_to :back
  end

  def open
    TimeSheet.create(user: current_user)
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_sheet
      @time_sheet = TimeSheet.includes(:user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_sheet_params
      params.require(:time_sheet).permit(:closed_at, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/time_sheets_helper.rb
module TimeSheetsHelper
  def format_time_sheet(end_time, start_time, lunch_time = 0)
    format_time(end_time.to_i - start_time.to_i - lunch_time)
  end

  def format_time(value)
    "#{(value/3600)}h #{(value%3600)/60}m"
  end
end

app/views/home/show.html.erb
<% if current_user %>
<!--   <div class="col-md-2">
    <dl>
      <dt>Today's Tasks</dt>
      <dd class="bg-success"><input type="checkbox" checked/> Lorem ipsum</dd>
      <dd><input type="checkbox"/> Lorem ipsum</dd>
      <dd><input type="checkbox"/> Lorem ipsum</dd>
      <dd><input type="checkbox"/> Lorem ipsum</dd>
      <dd><input type="checkbox"/> Lorem ipsum</dd>
      <dd><input type="checkbox"/> Lorem ipsum</dd>
      <dd><input type="checkbox"/> Lorem ipsum</dd>
    </dl>
  </div> -->
  <div class="col-md-12">
    <div class="col-md-12 text-center">
      <% if @today %>
        <% if @today.closed_at.nil? %>
          <h2 data-created-at="<%= @today.created_at.to_i*1000 %>"> 
            Você tem uma sessão aberta desde <%= l @today.created_at, format: :time %>
          </h2>
          <%= link_to 'Encerrar', close_time_sheet_path(@today), class: 'btn btn-info' %>
        <% end %>
      <% else %>
          <h2> 
            <%= link_to 'Iniciar Sessão', open_time_sheet_path, class: 'btn btn-success' %>
          </h2>
      <% end %>
    </div>
    <div class="col-md-12" style="margin-top: 20px;">
      <table class="table">
          <% 
          beginning = nil
          total = 0
          @sheets.each do |sheet| %>
            <% if beginning != sheet.created_at.beginning_of_day %>
              <tr>
                <th colspan="3" class="text-center bg-success"><%= l sheet.created_at, format: :date %></th>
              </tr>
              <tr>
                <th>Início</th>
                <th>Fim</th>
                <th>Total</th>
              </tr>
            <% beginning = sheet.created_at.beginning_of_day %>
            <% end %>
            <tr>
              <td><%= l sheet.created_at, format: :time %></td>
              <td><%= l sheet.closed_at, format: :time %></td>
              <td><%= format_time_sheet(sheet.closed_at, sheet.created_at, 3600) %></td>
            </tr>
            <% total += (sheet.closed_at.to_i - sheet.created_at.to_i - 3600) %>
          <% end %>
      </table>
    </div>
  </div>
  <footer style="text-align: center; padding: 50px; font-size: 30px;">
    Total: <%= format_time(total) %>
  </footer>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Time Clock</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Time Clock</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
                </ul>
              </li>
              <li><%= image_tag(current_user.picture, size: "50x50") %></li>
            <% else %>
            <li><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/time_sheets/_form.html.erb
<%= form_for(@time_sheet) do |f| %>
  <% if @time_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_sheet.errors.count, "error") %> prohibited this time_sheet from being saved:</h2>

      <ul>
      <% @time_sheet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :closed_at %><br>
    <%= f.datetime_select :closed_at %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_sheets/edit.html.erb
<h1>Editing time_sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_sheet %> |
<%= link_to 'Back', time_sheets_path %>

app/views/time_sheets/index.html.erb
<h1>Listing time_sheets</h1>

<table>
  <thead>
    <tr>
      <th>Closed at</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @time_sheets.each do |time_sheet| %>
      <tr>
        <td><%= time_sheet.closed_at %></td>
        <td><%= time_sheet.user %></td>
        <td><%= link_to 'Show', time_sheet %></td>
        <td><%= link_to 'Edit', edit_time_sheet_path(time_sheet) %></td>
        <td><%= link_to 'Destroy', time_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time sheet', new_time_sheet_path %>

app/views/time_sheets/new.html.erb
<h1>New time_sheet</h1>

<%= render 'form' %>

<%= link_to 'Back', time_sheets_path %>

app/views/time_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Closed at:</strong>
  <%= @time_sheet.closed_at %>
</p>

<p>
  <strong>User:</strong>
  <%= @time_sheet.user %>
</p>

<%= link_to 'Edit', edit_time_sheet_path(@time_sheet) %> |
<%= link_to 'Back', time_sheets_path %>